language: ruby
rvm:
  - 2.6.0
script:
  - bundle exec jekyll build --future
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --url-ignore "/#.*/"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - gh-pages
  - /.*/
notifications:
  on_success: never
  on_failure: always
